# Importing and cleaning data
This notebook will clean data from the California Department of Education for the analysis. Our goal is to merge all the data into a single cohesive geodataframe, which will happen in a subsequent notebook.  

 - [lcff data](https://ias.cde.ca.gov/lcffsnapshot/lcff.aspx)
 - [grades](https://www.cde.ca.gov/ta/ac/cm/datafilesfall18.asp)
 - [demographics/shapefiles](https://gis.data.ca.gov/datasets/e9476c422f0842a7a38652aaf4c7597c_0?geometry=-174.879%2C31.049%2C-63.126%2C43.258)
 
Datasets last downloaded - 9/2/20

In [26]:
import pandas as pd
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_column', 200)

## LCFF data

In [27]:
lcff = pd.read_csv('raw_data/lcffsnapshot18an.csv')
# import lcff data from source

In [28]:
lcff.columns = lcff.columns.str.strip()
# strip leading/trailing spaces

In [29]:
lcff.drop(lcff.tail(1).index,inplace=True)
# extracting state totals, removing from df

In [30]:
lcff.head()

,County Code,District Code,School Code,Local Educational Agency,Charter Number,"TK/K-3 ADA\nTarget, B-5/B-1","4 - 6 ADA\nTarget, B-6/B-2","7 - 8 ADA\nTarget, B-7/B-3","9 - 12 ADA\nTarget, B-8/B-4","Unduplicated Pupil Percentage\nTarget, D-1","Base Grant Funding\nTarget, C-5","Supplemental Grant Funding\nTarget, D-7","Concentration Grant Funding\nTarget, E-8","Necessary Small Schools Allowance\nTarget, F-1","Add-On (Based on 2012-13 Targeted Instructional Improvement Block Grant)\nTarget, F-2","Add-On (Based on 2012-13 Home-to-School Transportation)\nTarget, F-3","Add-On (Based on 2012-13 Small School District Bus Replacement Program)\nTarget, F-4","Total LCFF Target Entitlement\nTarget, G-1/F-1","Total LCFF Floor Entitlement\nTransition, B-13","Current Year Gap Funding (100%)\nTransition, C-3","Economic Recovery Target\nTransition, D-1","Miscellaneous Adjustments\nTransition, E-1","Total Local Revenue or In-Lieu of Property Taxes\nTransition, F-2/F-7","Education Protection Account Entitlement\nTransition, F-5/F-9","Net State Aid\nTransition, F-6/F-10","Additional SA for MSA Guarantee\nTransition, H-1/H-2"
0,01,10017.0,112607.0,Envision Academy for Arts & Technology,811.0,-,-,-,359.23,0.7785,"$3,329,703","$518,435","$362,605",N/A,N/A,N/A,N/A,"$4,210,743","$3,871,076","$339,667",$-,$-,"$894,989","$683,070","$2,632,684",$-
1,01,10017.0,123968.0,Community School for Creative Education,1284.0,125.80,66.49,32.89,-,0.7936,"1,795,769","285,024","195,559",N/A,N/A,N/A,N/A,"2,276,352","2,124,388","151,964",-,-,"561,016","354,307","1,361,029",-
2,01,10017.0,124172.0,Yu Ming Charter,1296.0,252.38,134.11,48.83,-,0.1892,"3,474,375","131,471",-,N/A,N/A,N/A,N/A,"3,605,846","3,388,539","217,307",-,-,-,"683,750","2,922,096",-
3,01,10017.0,125567.0,Urban Montessori Charter,1383.0,271.70,101.50,26.45,-,0.3756,"3,212,111","241,293",-,N/A,N/A,N/A,N/A,"3,453,404","3,238,948","214,456",-,-,"995,692","627,724","1,829,988",-
4,01,10017.0,131581.0,Oakland Unity Middle School,1707.0,-,61.99,109.29,-,0.9199,"1,321,351","243,103","143,896",N/A,N/A,N/A,N/A,"1,708,350","1,620,979","87,371",-,-,"426,729","34,256","1,247,365",-

In [31]:
lcff = lcff.fillna(0)
lcff['County Code'] = lcff['County Code'].astype(str)
lcff['District Code'] = lcff['District Code'].astype(int)
lcff['District Code'] = lcff['District Code'].astype(str)
lcff['School Code'] = lcff['School Code'].astype(int)
lcff['School Code'] = lcff['School Code'].astype(str)
# changing to strings
# slicing by district level cds code

In [32]:
lcff['School Code'] = lcff['School Code'].apply(lambda x: '{0:0>7}'.format(x))
# front fill school codes to == 7

In [33]:
lcff

,County Code,District Code,School Code,Local Educational Agency,Charter Number,"TK/K-3 ADA\nTarget, B-5/B-1","4 - 6 ADA\nTarget, B-6/B-2","7 - 8 ADA\nTarget, B-7/B-3","9 - 12 ADA\nTarget, B-8/B-4","Unduplicated Pupil Percentage\nTarget, D-1","Base Grant Funding\nTarget, C-5","Supplemental Grant Funding\nTarget, D-7","Concentration Grant Funding\nTarget, E-8","Necessary Small Schools Allowance\nTarget, F-1","Add-On (Based on 2012-13 Targeted Instructional Improvement Block Grant)\nTarget, F-2","Add-On (Based on 2012-13 Home-to-School Transportation)\nTarget, F-3","Add-On (Based on 2012-13 Small School District Bus Replacement Program)\nTarget, F-4","Total LCFF Target Entitlement\nTarget, G-1/F-1","Total LCFF Floor Entitlement\nTransition, B-13","Current Year Gap Funding (100%)\nTransition, C-3","Economic Recovery Target\nTransition, D-1","Miscellaneous Adjustments\nTransition, E-1","Total Local Revenue or In-Lieu of Property Taxes\nTransition, F-2/F-7","Education Protection Account Entitlement\nTransition, F-5/F-9","Net State Aid\nTransition, F-6/F-10","Additional SA for MSA Guarantee\nTransition, H-1/H-2"
0,01,10017,0112607,Envision Academy for Arts & Technology,811.0,-,-,-,359.23,0.7785,"$3,329,703","$518,435","$362,605",N/A,N/A,N/A,N/A,"$4,210,743","$3,871,076","$339,667",$-,$-,"$894,989","$683,070","$2,632,684",$-
1,01,10017,0123968,Community School for Creative Education,1284.0,125.80,66.49,32.89,-,0.7936,"1,795,769","285,024","195,559",N/A,N/A,N/A,N/A,"2,276,352","2,124,388","151,964",-,-,"561,016","354,307","1,361,029",-
2,01,10017,0124172,Yu Ming Charter,1296.0,252.38,134.11,48.83,-,0.1892,"3,474,375","131,471",-,N/A,N/A,N/A,N/A,"3,605,846","3,388,539","217,307",-,-,-,"683,750","2,922,096",-
3,01,10017,0125567,Urban Montessori Charter,1383.0,271.70,101.50,26.45,-,0.3756,"3,212,111","241,293",-,N/A,N/A,N/A,N/A,"3,453,404","3,238,948","214,456",-,-,"995,692","627,724","1,829,988",-
4,01,10017,0131581,Oakland Unity Middle School,1707.0,-,61.99,109.29,-,0.9199,"1,321,351","243,103","143,896",N/A,N/A,N/A,N/A,"1,708,350","1,620,979","87,371",-,-,"426,729","34,256","1,247,365",-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242,STATE TOTALS,0,0000000,0,0.0,"1,813,000.84","1,361,446.53","923,799.16","1,855,585.57",0,"$49,569,226,529","$6,189,112,345","$3,473,165,908","$100,474,970","$855,045,830","$461,199,504","$4,112,421","$60,652,337,507","$56,805,139,260","$3,934,385,946","$45,891,349","$(134,316)","$20,313,234,098","$7,649,112,824","$33,596,775,929","$144,408,593"
2243,NOTE: Some LEAs may not display funding data d...,0,0000000,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2244,Prepared by:,0,0000000,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2245,California Department of Education,0,0000000,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2246,School Fiscal Services Division,0,0000000,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
lcff = lcff.loc[lcff['School Code'] == '0000000']
# select districts, district entries do not have a school level cds code

In [35]:
lcff['cds'] = lcff['County Code'] + lcff['District Code'] + lcff['School Code']
# combining into full cds code
col_name='cds'
first_col = lcff.pop(col_name)
lcff.insert(0, col_name, first_col)
# moving to front
lcff.drop('County Code', axis=1, inplace=True)
lcff.drop('School Code', axis=1, inplace=True)
# dropping excess

C:\Users\fiend\Anaconda2\envs\capstone\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\fiend\Anaconda2\envs\capstone\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [36]:
lcff = lcff.rename(columns={'Charter Number': 'charter_number',
                     'Unduplicated Pupil Percentage\nTarget, D-1': 'unduplicated_pupil_percentage',
                     'Base Grant Funding\nTarget, C-5': 'base_grant',
                     'Supplemental Grant Funding\nTarget, D-7': 'supplemental_grant',
                     'Concentration Grant Funding\nTarget, E-8': 'concentration_grant',
                     'Total LCFF Target Entitlement\nTarget, G-1/F-1': 'total_grants',
                     'Necessary Small Schools Allowance\nTarget, F-1': 'nec_small_schools',
                     'Local Educational Agency' : 'districtname'      
                           })

In [45]:
lcff.tail(7)
# gotta drop the last 5 rows

,districtname,unduplicated_pupil_percentage,base_grant,supplemental_grant,concentration_grant,total_grants,cds
2228,Winters Joint Unified,0.6912,"12,381,934","1,711,677","874,165","15,184,247",57727020000000
2229,Woodland Joint Unified,0.6751,"77,255,593","10,431,050","4,832,338","93,665,089",57727100000000
2233,Camptonville Elementary,0.6988,"420,692","58,796","31,299","537,244",58727280000000
2235,Marysville Joint Unified,0.8168,"76,193,862","12,447,028","10,164,261","100,261,913",58727360000000
2238,Plumas Lake Elementary,0.3868,"10,261,440","793,825",-,"11,108,901",58727440000000
2239,Wheatland,0.4783,"9,947,133","951,543",-,"11,234,349",58727510000000
2241,Wheatland Union High,0.4283,"7,062,422","604,967",-,"7,852,628",58727690000000

In [44]:
lcff.drop(lcff.tail(5).index,inplace=True)

In [46]:
# renaming for readability
lcff = lcff[[  'districtname',
               'unduplicated_pupil_percentage', 
               'base_grant', 
               'supplemental_grant', 
               'concentration_grant', 
               'total_grants', 
               'cds' ]].copy()
# copying relevant columns into a new dataframe

lcff['cds'] = lcff['cds'].astype(float)

In [47]:
lcff.to_csv("clean_data/lcff.csv")
# save to disk

## Grade data

Math first

In [48]:
math = pd.read_csv('raw_data/mathdownload2018.csv')

C:\Users\fiend\Anaconda2\envs\capstone\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6,23) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

This cell created a dictionary to replace the abbreviated student codes with more descriptive names. I do not use it because in a later data structure, the abbreviated names are more concise when indicating either math or english, AND current vs prior vs change grades, but I retain the cell here in case I want to use this format to execute column name replacements in the future.

replacements = dict(
    studentgroup = {'ALL':'all_students',
                        'AA':'african_american',
                        'AI':'american_indian',
                        'AS':'asian',
                        'FI':'filipino',
                        'HI':'hispanic',
                        'PI':'pacific_islander',
                        'WH':'white',
                        'MR':'multiple_races',
                        'EL':'english_learners',
                        'ELO':'english_learners_only',
                        'RFP':'rfep_only',
                        'EO':'english_only',
                        'SED':'ses_disad',
                        'SWD':'disabilities',
                        'FOS':'foster_youth',
                        'HOM':'homeless_youth',
                })
                
                
math['studentgroup'].astype(str)
math = math.replace(replacements)
# replace student group codes

fixing cds codes to match to enable merges

In [49]:
math['cds'].astype(str)
# changing to string
math = math[math.coe_flag !='Y']
# removing county offices of education
math = math.loc[math['rtype'] == 'D']
# select district-level performance
math['cds'] = math['cds'].apply(lambda x: '{0:0>14}'.format(x))
# adding leading zero to 13 digit int
math['District Code'] = [x[2:7] for x in math['cds']]
# adding district only code

In [50]:
math = pd.concat([math.pop(x) for x in ['District Code',
                                          'districtname',                                          
                                          'studentgroup', 
                                          'currstatus', 
                                          'priorstatus', 
                                          'change',
                                          'countyname']],
                    1)
# slice out columns

In [51]:
math

,District Code,districtname,studentgroup,currstatus,priorstatus,change,countyname
163,61119,Alameda Unified,AA,-83.9,-82.8,-1.1,Alameda
164,61119,Alameda Unified,AI,-51.8,-50.0,-1.8,Alameda
165,61119,Alameda Unified,ALL,14.3,10.8,3.4,Alameda
166,61119,Alameda Unified,AS,43.6,44.8,-1.2,Alameda
167,61119,Alameda Unified,EL,-13.7,-12.9,-0.9,Alameda
...,...,...,...,...,...,...,...
148683,72769,Wheatland Union High,PI,NaN,NaN,NaN,Yuba
148684,72769,Wheatland Union High,RFP,NaN,NaN,NaN,Yuba
148685,72769,Wheatland Union High,SED,-90.0,-74.0,-16.0,Yuba
148686,72769,Wheatland Union High,SWD,-226.6,NaN,NaN,Yuba
148687,72769,Wheatland Union High,WH,-42.3,-57.0,14.7,Yuba

In [52]:
math.to_csv("clean_data/math.csv")
# save to disk

English grades now

In [53]:
ela = pd.read_csv('raw_data/eladownload2018.csv')

C:\Users\fiend\Anaconda2\envs\capstone\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6,23) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

fixing cds codes to match to enable merges

In [54]:
ela['cds'].astype(str)
# changing cds code to string
ela = ela[ela.coe_flag !='Y']
# removing county offices of education
ela = ela.loc[ela['rtype'] == 'D']
# select district level entries
ela['cds'] = ela['cds'].apply(lambda x: '{0:0>14}'.format(x))
# adding leading zero to 13 digit int
ela['District Code'] = [x[2:7] for x in ela['cds']]

In [55]:
#creating district-level ela performance variable (dictionary)
ela = pd.concat([ela.pop(x) for x in ['District Code',
                                          'districtname',                                          
                                          'studentgroup', 
                                          'currstatus', 
                                          'priorstatus', 
                                          'change',
                                          'countyname']],
                    1)
# slice out columns

In [56]:
ela.to_csv("clean_data/ela.csv")
# save to disk

## Student attribute and shapefile data

This requires geopandas.

In [57]:
import geopandas as gpd

In [58]:
t = gpd.read_file("raw_data/DistrictAreas1819.shp")

In [59]:
t.to_file("clean_data/attributes.shp")
# save to disk

## Downloading the ltdb with Geosnap

We need to download the data that geosnap uses to construct its 'commuinity' class. see the [geosnap user guide](https://spatialucr.github.io/geosnap-guide/content/01_getting_started.html)

In [12]:
from geosnap.io import store_ltdb

In [13]:
sample = "D:/github/finalcapstone/raw_data/LTDB_Std_All_Sample.zip"
full = "D:/github/finalcapstone/raw_data/LTDB_Std_All_fullcount.zip"
# definitely add these files to the .gitignore file

geosnap.io.store_ltdb(sample=sample, fullcount=full)

Hashing: 100%|██████████| 300M/300M [00:00<00:00, 447MB/s]